% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Feb-2023 17:49:46
%  MATLAB version: 9.13.0.2166757 (R2022b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('hydrolic_power_plant.mat');

Dh = 0.5;

I_wheel = 1915;

K_gen = 0.2;

R_gear = 0.01;

T_nominal = 50;

b = 10;

g = 9.81;

h_res = 100;

out = saveVarsMat.out; 

pipe_length = 20;

r_load = 100;

rho = 1000;

vol_displacement = 1.5;

